languages:
  Python: true
exclude_paths:
- "telegram/emoji.py"
- "tests/*"
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python:
    checks:
      Similar code:
        enabled: false

  radon:
    enabled: true
    config:
      threshold: "C"