-   repo: git://github.com/pre-commit/mirrors-yapf
    sha: 'v0.7.1'
    hooks:
    -   id: yapf

-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 'v0.5.0'
    hooks:
    -   id: flake8
        args: ['telegram']

-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: 'v1.5.5'
    hooks:
    -   id: pylint
        args: ['--errors-only', '--disable=no-name-in-module,import-error', 'telegram']