language: python
os:
  - linux
  - osx
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
install:
  - pip install pylint flake8 coveralls
  - pip install -r requirements.txt
script:
  nosetests --with-coverage --cover-package telegram/
  pylint -E telegram
  flake8 telegram
after_success:
  coveralls
