language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy-5.7.1"
  - "pypy3.5-5.8.0"

dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install coveralls
  - pip install -U wheel
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then pip install ujson; fi

script:
  - python travis.py

after_success:
  coveralls