language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
branches:
  only:
    - master
install:
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then pip install ujson; fi
script:
  - nosetests -v --with-flaky --no-flaky-report --with-coverage --cover-package=telegram/
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pre-commit run --all-files; fi
after_success:
  coveralls
